[package]
name = "wol"
version = "0.2.0"
authors = ["蔡斌卿 <caibinqing@live.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
eui48 = "1.1.0"

[dev-dependencies]
rand = "0.8.5"
